// lib/main.dart
// ignore_for_file: unused_import

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'package:myapp/screens/welcome_screen.dart';
import 'package:myapp/screens/auth_screen.dart'; // Handles both login and register
import 'package:myapp/screens/home_screen.dart'; // New screen after login
import 'package:myapp/firebase_options.dart'; // Auto-generated by FlutterFire CLI

// --- Define Custom Color Palette ---
const Color primaryBlue = Color(0xFF2A629A);       // A deeper, more sophisticated blue
const Color secondaryGreen = Color(0xFF388E3C);    // A rich, earthy green for success/sustainability
const Color accentGold = Color(0xFFD4AF37);        // A soft, elegant gold accent
const Color lightBackground = Color(0xFFF0F2F5);   // A very light, subtle grey-blue for backgrounds
const Color darkText = Color(0xFF333333);          // Dark text for readability
const Color lightText = Color(0xFFFFFFFF);         // Light text for dark backgrounds

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // --- Initialize Firebase ---
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // --- End Firebase Initialization ---

  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.light,
    systemNavigationBarColor: Colors.black,
    systemNavigationBarIconBrightness: Brightness.light,
  ));

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'My App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: primaryBlue,
        canvasColor: lightBackground,
        scaffoldBackgroundColor: lightBackground,

        colorScheme: ColorScheme.light(
          primary: primaryBlue,
          secondary: secondaryGreen,
          tertiary: accentGold,
          surface: Colors.white,
          onPrimary: lightText,
          onSecondary: lightText,
          onSurface: darkText,
          error: Colors.red.shade700,
          onError: lightText,
        ),

        textTheme: const TextTheme(
          displayLarge: TextStyle(fontSize: 57, color: darkText, fontWeight: FontWeight.bold),
          displayMedium: TextStyle(fontSize: 45, color: darkText, fontWeight: FontWeight.bold),
          displaySmall: TextStyle(fontSize: 36, color: darkText, fontWeight: FontWeight.bold),
          headlineLarge: TextStyle(fontSize: 32, color: darkText, fontWeight: FontWeight.bold),
          headlineMedium: TextStyle(fontSize: 28, color: darkText, fontWeight: FontWeight.bold),
          headlineSmall: TextStyle(fontSize: 24, color: darkText, fontWeight: FontWeight.bold),
          titleLarge: TextStyle(fontSize: 22, color: darkText, fontWeight: FontWeight.bold),
          titleMedium: TextStyle(fontSize: 16, color: darkText, fontWeight: FontWeight.w600),
          titleSmall: TextStyle(fontSize: 14, color: darkText, fontWeight: FontWeight.w600),
          bodyLarge: TextStyle(fontSize: 16, color: darkText),
          bodyMedium: TextStyle(fontSize: 14, color: darkText),
          bodySmall: TextStyle(fontSize: 12, color: darkText),
          labelLarge: TextStyle(fontSize: 14, color: lightText, fontWeight: FontWeight.bold),
          labelMedium: TextStyle(fontSize: 12, color: darkText),
          labelSmall: TextStyle(fontSize: 11, color: darkText),
        ),

        appBarTheme: const AppBarTheme(
          backgroundColor: primaryBlue,
          elevation: 4,
          foregroundColor: lightText,
          titleTextStyle: TextStyle(color: lightText, fontSize: 20, fontWeight: FontWeight.bold),
        ),

        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: primaryBlue,
            foregroundColor: lightText,
            padding: const EdgeInsets.symmetric(vertical: 18),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(15),
            ),
            elevation: 8,
            shadowColor: primaryBlue.withOpacity(0.5),
            textStyle: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
          ),
        ),
        outlinedButtonTheme: OutlinedButtonThemeData(
          style: OutlinedButton.styleFrom(
            foregroundColor: primaryBlue,
            side: const BorderSide(color: primaryBlue, width: 2),
            padding: const EdgeInsets.symmetric(vertical: 18),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            elevation: 0,
            textStyle: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
          ),
        ),

        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: Colors.white,
          labelStyle: TextStyle(color: darkText.withOpacity(0.7)),
          hintStyle: TextStyle(color: darkText.withOpacity(0.4)),
          prefixIconColor: primaryBlue.withOpacity(0.7),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide(color: primaryBlue.withOpacity(0.3)),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide(color: primaryBlue.withOpacity(0.3)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: primaryBlue, width: 2),
          ),
          errorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide(color: Colors.red.shade700, width: 2),
          ),
          focusedErrorBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide(color: Colors.red.shade700, width: 2),
          ),
          contentPadding: const EdgeInsets.symmetric(vertical: 16.0, horizontal: 20.0),
        ),
      ),
      // --- Firebase Auth Stream Listener for initial routing ---
      home: StreamBuilder(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasData) {
            // User is logged in, go to HomeScreen
            return const HomeScreen();
          }
          // User is not logged in, show Welcome Screen
          return const WelcomeScreen();
        },
      ),
      // --- End Stream Listener ---
    );
  }
}